apiVersion: v1 
kind: Pod
metadata:
   name: web-pod
   labels:
      app: web
      tier: frontend 
spec:
   containers:
      - name: web 
        image: nginx:latest
        ports:
        - containerPort: 80


---
# lets talk about the probes
        