apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: web
spec:
  containers:
  - name: web
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  
  - name: content-generator
    image: busybox
    command: ['sh', '-c', 'while true; do echo "The time is now $(date)" > /data/index.html; sleep 30; done']
    volumeMounts:
    - name: shared-data
      mountPath: /data
  
  volumes:
  - name: shared-data
    emptyDir: {}

# kubectl port-forward multi-container-pod 8080:80